### ISSUE TITLE
Type Annotation Help

### ISSUE THREAD

**Issue by milesfrain** [paluh/purescript-homogeneous#1]
This works:
```purs
main = logShow $ toRecord $ map head $ homogeneous {a: [1], b: [2, 3]}
-- { a: (Just 1), b: (Just 2) }
```

But how can I make this mapping into a helper function? This requires type annotation:
```purs
recHeads rec = toRecord $ map head $ homogeneous rec
```

Here's one of my failing attempts:
```purs
recHeads :: forall a recShape recIn recOut.
  Fill (Array a) recShape recIn =>
  Fill (Maybe a) recShape recOut =>
  Record recIn -> Record recOut
recHeads rec = toRecord $ map head $ homogeneous rec
```

**Comment by paluh** [comment]
I'm afraid that we have to annotate one of the steps like `map head`:

``` purescript
recHeads :: forall a recShape recIn recOut .
  Row.Homogeneous recIn (Array a) =>
  Fill Void recIn recShape =>
  Fill (Maybe a) recShape recOut =>
  Record recIn -> Record recOut
recHeads rec = toRecord  $ (map head (homogeneous rec) ∷ Record.Homogeneous recShape (Maybe a))
```
or `homogeneous rec`:

``` purescript
recHeads' :: forall a recShape recIn recOut .
  Row.Homogeneous recIn (Array a) =>
  Fill Void recIn recShape =>
  Fill (Maybe a) recShape recOut =>
  Record recIn -> Record recOut
recHeads' rec = toRecord  $ map head $ (homogeneous rec ∷ Record.Homogeneous recShape (Array a))
```

I think that compiler needs a suggestion that `recShape` is in use during this transformation. Of course I could be wrong as I don't understand internals of the PS inference ;-)
A minor addition is also a `Row.Homogeneous recIn (Array a)` constraint which is required by `homogenous` itself.

**Comment by milesfrain** [comment]
Is there a way to write this point-free?

For reference, here are the two heterogeneous options:

Using a `Proxy` for generic `a`:
```purs
recHeads :: forall a recIn recOut.
  HMap (Array a -> Maybe a) recIn recOut =>
  Proxy a -> recIn -> recOut
recHeads _ = hmap (head :: Array a -> Maybe a)

main :: Effect Unit
main = logShow $ recHeads (Proxy :: _ Int) {a: [1], b: [2, 3]}
```
https://try.ps.ai/?gist=d9fffa03d87b74a86fd4ea08c7c79da7

Hardcoding `a` (to an `Int` in this case):
```purs
recHeads :: forall recIn recOut.
  HMap (Array Int -> Maybe Int) recIn recOut =>
  recIn -> recOut
recHeads = hmap (head :: Array Int -> Maybe Int)

main :: Effect Unit
main = logShow $ recHeads {a: [1], b: [2, 3]}
```
https://try.ps.ai/?gist=012c9a3f02a143ed56a93b4b51e26696

Both options need an annotation for `head`, but its still less verbose overall.

**Comment by paluh** [comment]
Miles, thanks a lot for your feedback!

> Is there a way to write this point-free?

Yeah, no problem:

```purescript
recHeads'' :: forall a recShape recIn recOut .
  Row.Homogeneous recIn (Array a) =>
  Fill Void recIn recShape =>
  Fill (Maybe a) recShape recOut =>
  Record recIn -> Record recOut
recHeads'' = toRecord  <<< map head <<< (homogeneous ∷ { | recIn } → Record.Homogeneous recShape (Array a))
```

> Both options need an annotation for head, but its still less verbose overall.

It is worth noting that _heterogeneous_ provides a dedicated `class` for mapping records. With _homogeneous_ we just use the `map` member of the `Functor`. As I stated above I can provide dedicated `class` which "hides" the above constraints complexity:

```purescript
class HomogeneousMap a b recIn recOut | b recIn → recOut, a recOut → recIn, recIn -> a, recOut → b where
  homogeneousMap :: (a → b) → { | recIn } → { | recOut }

instance homogeneousMapInstance
  ∷ ( Row.Homogeneous recIn a
    , Fill Void recIn recShape
    , Fill b recShape recOut
    )
  ⇒ HomogeneousMap a b recIn recOut where
  homogeneousMap f
    = toRecord
    <<< map f
    <<< (homogeneous ∷ { | recIn } → Record.Homogeneous recShape a)
```

so now I can just call it with single constraint which is unfortunately still required:

```purescript
recHeads''' :: forall a recIn recOut.
  HomogeneousMap  (Array a) (Maybe a) recIn recOut => { | recIn } -> { | recOut }
recHeads''' = homogeneousMap head
```

The question remains if it should be a part of this library. What do you think?

**Comment by milesfrain** [comment]
> The question remains if it should be a part of this library. What do you think?

I would definitely enjoy using that convenience function, but I see the concerns with bloating the library.

I think it would be most user-friendly if you could set up the constraints with records, rather than rows. And what about reusing names from heterogeneous? This version would be really ergonomic:
```purs
recHeads :: forall a recIn recOut.
  HMap (Array a) (Maybe a) recIn recOut =>
  recIn -> recOut
recHeads = hmap head
```

I haven't looked closely at record vs row feasibility yet though.

**Comment by paluh** [comment]
@milesfrain I've changed type level row representation to `SList` (a list of symbols from _record-extra_) and now your example seems to work without annotations: https://github.com/paluh/purescript-homogeneous/blob/master/test/Main.purs#L16

P.S.
I've also removed _typelevel-eval_ dependency and added a bunch of instances for `Variant.Homogeneous`.

**Comment by paluh** [comment]
Miles, I've just checked also a scenario where compiler doesn't know what is the expected type for the `recHeads`  call and it seems that this works fine too. What I mean is this scenario:

```purescript
  let
    recHeads rec = toRecord (map Array.head (Record.homogeneous rec))
  logShow $ recHeads { a: [ 1 ], b: [ 2, 3 ], c: [] }
```

Could you please tell me if you think that I can close this ticket?

**Comment by milesfrain** [comment]
Thanks. This looks good.

**Comment by paluh** [comment]
@milesfrain Just a quick update. I was able to provide more precise constraints for transformations between original `Row`s and library homogeneous `Row` but using `Row` back as a tag for the structure. In other words I've removed `SList` from the lib which is nice because we don't have to rely on an order of labels in this tag :-)

**Comment by paluh** [comment]
P.S.
Your previous examples are part of the regression so I'm sure that the inference works nicely after this change.
